version: 2

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
    timezone: Asia/Jakarta
  open-pull-requests-limit: 99
  target-branch: main
  reviewers:
    - Fab1o0107
  labels:
    - dependencies
  commit-message:
    prefix: chore
    include: scope
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
    timezone: Asia/Jakarta
  open-pull-requests-limit: 99
  target-branch: main
  reviewers:
    - Fab1o0107
  labels:
    - gh-actions
    - dependencies
  commit-message:
    prefix: ci
    include: scope
