name: Lint syntax rules

on:
  push:
    branches: main
  pull_request:
    branches: "**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3

    - name: Setup Node.js
      uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3
      with:
        check-latest: true

    - name: Install dependencies
      run: npm ci

    - name: Run lint
      run: npm run lint
