name: Lint syntax rules

on:
  push:
    branches:
     - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Config

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          check-latest: true

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint
