name: Lint syntax rules

on:
  push:
    branches:
     - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Config

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3

      - name: Setup Node.js
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          check-latest: true

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint
